function(get_xeon_version version_var)
  file(READ "${CMAKE_CURRENT_SOURCE_DIR}/include/xeon/version.h" version_header_file)
  foreach(component MAJOR MINOR PATCH)
    string(REGEX MATCH "#define XEON_${component} ([0-9]+)" _ ${version_header_file})
    set(XEON_VERSION_${component} ${CMAKE_MATCH_1})
  endforeach()
  set(${version_var} "${XEON_VERSION_MAJOR}.${XEON_VERSION_MINOR}.${XEON_VERSION_PATCH}" PARENT_SCOPE)
endfunction()
